import { ArrowRight, Check, ChevronRight, FlaskConical, Lightbulb, RotateCcw, Sparkles, Users } from 'lucide-react';
import { useState } from 'react';
import { Link } from 'wouter';
import { useFrameChallengeWithAi, type AiFrame } from '@workspace/api-client-react';

const examples = ['People in my neighborhood avoid the bus after dark', 'Small businesses cannot understand new climate rules', 'Students need more quiet places to work'];

export default function AiLab() {
  const [rawIdea, setRawIdea] = useState('');
  const [context, setContext] = useState('');
  const [frame, setFrame] = useState<AiFrame | undefined>();
  const ai = useFrameChallengeWithAi();
  const run = (event: React.FormEvent) => {
    event.preventDefault();
    ai.mutate({ data: { rawIdea, context } }, { onSuccess: (result) => setFrame(result) });
  };
  const reset = () => { setFrame(undefined); setRawIdea(''); setContext(''); };
  return (
    <div className="mx-auto max-w-[1200px] px-5 py-12 md:px-8 md:py-20">
      <div className="grid gap-12 md:grid-cols-[.8fr_1.2fr] md:items-start">
        <div className="md:sticky md:top-28"><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-[hsl(var(--accent))]"><FlaskConical size={21} /></span><span className="mono-font text-[10px] uppercase tracking-[.2em] text-[hsl(var(--primary))]">CivicForge / AI lab</span></div><h1 className="display-font mt-7 text-6xl leading-[.88] tracking-[-.06em] md:text-[84px]">Make the<br /><span className="text-[hsl(var(--primary))]">question</span><br />sharper.</h1><p className="mt-7 max-w-sm text-base leading-7 text-[hsl(var(--muted-foreground))]">Bring a hunch, a frustration, or a half-formed observation. Our framing assistant helps you find the challenge inside it.</p><div className="mt-9 flex items-start gap-3 text-xs leading-5 text-[hsl(var(--muted-foreground))]"><Sparkles size={16} className="mt-0.5 shrink-0 text-[hsl(var(--primary))]" /><span>AI offers a starting point, not a final answer. The people closest to the issue stay in charge.</span></div></div>
        <div>
          {!frame ? <form onSubmit={run} className="rounded-2xl border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-6 md:p-9"><div className="flex items-center justify-between border-b border-[hsl(var(--border))] pb-6"><div><h2 className="font-bold">Start with the rough edge</h2><p className="mt-1 text-xs text-[hsl(var(--muted-foreground))]">No jargon required.</p></div><span className="mono-font text-[10px] text-[hsl(var(--muted-foreground))]">01 / 02</span></div><label className="mt-8 grid gap-2"><span className="text-sm font-bold">What are you noticing?</span><textarea required minLength={10} rows={7} value={rawIdea} onChange={(event) => setRawIdea(event.target.value)} data-testid="input-ai-idea" placeholder="I keep noticing that..." className="focus-ring resize-none rounded-xl border border-[hsl(var(--border))] bg-[hsl(var(--background))] px-4 py-4 text-lg leading-7 outline-none placeholder:text-[hsl(var(--muted-foreground))] focus:border-[hsl(var(--primary))]" /></label><div className="mt-5 flex flex-wrap gap-2">{examples.map((example) => <button key={example} type="button" onClick={() => setRawIdea(example)} data-testid={`button-example-${examples.indexOf(example)}`} className="rounded-full border border-[hsl(var(--border))] px-3 py-2 text-left text-xs text-[hsl(var(--muted-foreground))] transition-colors hover:border-[hsl(var(--primary))] hover:bg-[hsl(var(--primary)/.06)]">{example}</button>)}</div><label className="mt-8 grid gap-2"><span className="text-sm font-bold">Add context <span className="font-normal text-[hsl(var(--muted-foreground))]">(optional)</span></span><input value={context} onChange={(event) => setContext(event.target.value)} data-testid="input-ai-context" placeholder="Who experiences it? Where? What have you tried?" className="focus-ring rounded-xl border border-[hsl(var(--border))] bg-[hsl(var(--background))] px-4 py-3.5 text-sm outline-none placeholder:text-[hsl(var(--muted-foreground))]" /></label>{ai.isError && <p className="mt-5 text-sm text-[hsl(var(--destructive))]" data-testid="status-ai-error">The lab is taking a breath. Try submitting once more.</p>}<button type="submit" disabled={ai.isPending} data-testid="button-frame-with-ai" className="mt-8 flex w-full items-center justify-center gap-2 rounded-xl bg-[hsl(var(--foreground))] px-5 py-4 text-sm font-bold text-[hsl(var(--background))] transition-transform hover:-translate-y-0.5 disabled:opacity-60">{ai.isPending ? 'Finding the useful edges...' : 'Shape this into a challenge'} <ArrowRight size={17} /></button></form> : <FrameResult frame={frame} reset={reset} /> }
          <div className="mt-5 flex items-center gap-2 text-[11px] text-[hsl(var(--muted-foreground))]"><Lightbulb size={14} className="text-[hsl(var(--accent-foreground))]" /> You can edit every word before you share it.</div>
        </div>
      </div>
    </div>
  );
}

function FrameResult({ frame, reset }: { frame: AiFrame; reset: () => void }) {
  return <div className="overflow-hidden rounded-2xl border border-[hsl(var(--foreground))] bg-[hsl(var(--foreground))] text-[hsl(var(--background))] shadow-[8px_8px_0_hsl(var(--primary))]" data-testid="panel-ai-result"><div className="flex items-center justify-between border-b border-[hsl(var(--background)/.16)] px-6 py-5 md:px-8"><div className="flex items-center gap-2 text-[hsl(var(--accent))]"><Check size={16} /><span className="mono-font text-[10px] uppercase tracking-[.18em]">A first frame</span></div><button type="button" onClick={reset} data-testid="button-reset-ai" className="flex items-center gap-1.5 text-xs text-[hsl(var(--background)/.6)] hover:text-[hsl(var(--background))]"><RotateCcw size={13} /> Start over</button></div><div className="p-6 md:p-8"><h2 className="display-font text-4xl leading-[.98] tracking-[-.05em] md:text-5xl">{frame.title}</h2><div className="mt-8 border-l-2 border-[hsl(var(--accent))] pl-5"><p className="text-sm leading-7 text-[hsl(var(--background)/.78)]">{frame.framing}</p></div><div className="mt-10 grid gap-8 md:grid-cols-2"><div><p className="mono-font text-[10px] uppercase tracking-[.18em] text-[hsl(var(--accent))]">Possible outcomes</p><div className="mt-4 grid gap-3">{frame.outcomes.map((outcome) => <div key={outcome} className="flex gap-2 text-sm leading-6"><ChevronRight size={16} className="mt-1 shrink-0 text-[hsl(var(--accent))]" /> {outcome}</div>)}</div></div><div><p className="mono-font text-[10px] uppercase tracking-[.18em] text-[hsl(var(--accent))]">Useful next connections</p><div className="mt-4 grid gap-2">{frame.suggestedPartners.map((partner) => <div key={partner} className="flex items-center gap-2 rounded-lg bg-[hsl(var(--background)/.08)] px-3 py-2.5 text-sm"><Users size={14} className="text-[hsl(var(--accent))]" /> {partner}</div>)}</div><div className="mt-5 flex flex-wrap gap-2">{frame.tags.map((tag) => <span key={tag} className="rounded-full border border-[hsl(var(--background)/.2)] px-2.5 py-1 text-[10px] uppercase tracking-[.08em] text-[hsl(var(--background)/.7)]">{tag}</span>)}</div></div></div><Link href="/submit" data-testid="link-turn-ai-result-into-challenge" className="mt-10 flex items-center justify-center gap-2 rounded-xl bg-[hsl(var(--accent))] px-5 py-4 text-sm font-bold text-[hsl(var(--foreground))]">Take this to the submit form <ArrowRight size={17} /></Link></div></div>;
}