import { useState } from "react";
import { Link, useLocation } from "wouter";
import { Building2, Users, ShieldCheck, LogOut } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { useAuth } from "@/lib/auth-context";
import { demoIndustry, demoLabels, demoUniversity, useDemoSession } from "@/lib/demo-session";
import { demoStudents, useDemoWorkspace } from "@/lib/demo-workspace";

export default function DemoPortal() {
  const { demoSession, endDemoSession } = useDemoSession();
  const { setLoginModalOpen } = useAuth();
  const [, navigate] = useLocation();
  const role = demoSession!.role;
  const { workspace, update, error } = useDemoWorkspace(role);
  const [selected, setSelected] = useState("water");
  const [reason, setReason] = useState("");
  const [student, setStudent] = useState(demoStudents[0]);
  const project = workspace.projects.find(p => p.id === selected)!;
  const mutate = (action: string, change: Parameters<typeof update>[2]) => update(project.id, action, change);
  const mentors = project.mentors.filter(m => !m.end);
  const titles = { citizen: "Citizen dashboard", officer: "Officer dashboard", admin: "Government dashboard", university_admin: "University dashboard", industry_partner: "Industry dashboard" };
  const entity = role === "university_admin" ? demoUniversity : role === "industry_partner" ? demoIndustry : null;
  const accepted = project.assignment === "accepted";
  const canDevelop = accepted && project.students.length > 0 && mentors.length > 0;
  return <div className="noise-layer min-h-screen bg-[hsl(var(--background))] text-[hsl(var(--foreground))]">
    <header className="border-b bg-[hsl(var(--card))]"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-3 p-5">
      <span className="display-font text-2xl font-bold">JANSAMVAD</span>
      <span className="flex items-center gap-2 text-sm"><ShieldCheck size={17} />Active demo role: <strong data-testid="demo-role">{role === "admin" ? "ADMIN / SUPER_ADMIN" : role.toUpperCase()}</strong></span>
      <div className="flex flex-wrap gap-2"><Button variant="outline" data-testid="demo-role-switch" onClick={() => setLoginModalOpen(true)}>Role / Portal</Button><Button variant="outline" data-testid="demo-logout" onClick={() => { endDemoSession(); navigate("/"); }}><LogOut size={16} className="mr-2" />Log out demo</Button></div>
    </div></header>
    <main className="mx-auto max-w-7xl space-y-6 p-4 sm:p-8">
      <div><Badge variant="outline">Societal Innovation Ecosystem</Badge><h1 className="display-font mt-3 text-3xl font-bold">{titles[role]}</h1><p className="mt-2 text-sm text-[hsl(var(--muted-foreground))]">{demoSession!.profile.full_name} · {demoSession!.profile.email} · Ranchi</p></div>
      {entity && <Card><CardContent className="pt-6"><p className="flex items-center gap-2 font-bold"><Building2 size={20} />{entity.name}</p><p className="mt-2 text-xs">Data origin: {entity.dataOrigin} · Verification: {entity.verificationStatus} · Fictional demo organization</p><p data-testid="demo-entity-link" className="mt-1 text-xs text-[hsl(var(--muted-foreground))]">Linked demo profile: {role === "university_admin" ? demoSession!.profile.university_id : demoSession!.profile.industry_partner_id}</p></CardContent></Card>}
      <div className="grid gap-4 sm:grid-cols-3">{[
        `${workspace.projects.length} demo challenges`,
        `${workspace.projects.filter(p => p.assignment === "accepted").length} accepted assignments`,
        `${workspace.projects.reduce((n,p) => n + p.milestones.filter(m => m.completed).length,0)} completed milestones`,
      ].map(text => <Card key={text}><CardContent className="pt-6 font-bold">{text}</CardContent></Card>)}</div>
      <p className="text-sm text-[hsl(var(--muted-foreground))]">Demo changes survive refresh and role switching in this tab. They are never sent to production. <Link className="underline" href={`/demo/${role}`}>Open demo preview</Link></p>
      {error && <p role="alert" className="text-red-600">{error}</p>}
      <div className="grid items-start gap-5 lg:grid-cols-[320px_1fr]">
        <Card><CardHeader><CardTitle>{role === "industry_partner" ? "Recommended projects" : role === "university_admin" ? "University assignments" : "Community challenges"}</CardTitle></CardHeader><CardContent className="space-y-3">{workspace.projects.map(p => <button key={p.id} onClick={() => { setSelected(p.id); setReason(""); }} aria-pressed={selected === p.id} className={`w-full space-y-2 rounded-xl border p-4 text-left ${selected === p.id ? "border-[hsl(var(--primary))] bg-[hsl(var(--primary)/.06)]" : ""}`}><strong className="block text-sm">{p.title}</strong><span className="block text-xs">{p.location} · {p.category}</span><Badge variant="outline">{p.status}</Badge></button>)}</CardContent></Card>
        <div className="space-y-5"><Card><CardHeader><CardTitle>{project.title}</CardTitle><p className="text-sm text-[hsl(var(--muted-foreground))]">{project.description}</p></CardHeader><CardContent className="space-y-4">
          <div className="flex flex-wrap gap-2"><Badge>{project.status}</Badge><Badge variant="outline">AI priority: High (demo)</Badge><Badge variant="secondary">Community votes: {project.votes}</Badge></div>
          {role === "citizen" && <><p className="text-sm">Explore validated demo challenges and help prioritize community projects.</p><Button data-testid="demo-vote" disabled={project.voted} onClick={() => mutate("Citizen voted", p => { p.voted = true; p.votes += 1; })}>{project.voted ? "Voted" : "Vote for this project"}</Button></>}
          {role === "officer" && <><p className="text-sm">Inspect the challenge and route it to the demo university for evaluation.</p><div className="flex flex-wrap gap-2"><Button onClick={() => mutate("Inspection completed", p => { p.status = "Inspected"; })}>Complete inspection</Button><Button variant="outline" onClick={() => mutate("Routed to demo university", p => { p.status = "Assigned"; p.assignment = "pending"; })}>Route to university</Button></div></>}
          {role === "university_admin" && <><p className="text-sm">Assignment: <strong>{project.assignment.replaceAll("_", " ")}</strong></p>{project.reason && <p className="text-sm">Note: {project.reason}</p>}{!accepted && <><Input aria-label="Assignment reason" placeholder="Reason for rejection or information request" value={reason} onChange={e => setReason(e.target.value)} /><div className="flex flex-wrap gap-2"><Button data-testid="demo-accept" onClick={() => mutate("University accepted assignment", p => { p.assignment = "accepted"; p.status = "Assigned"; p.reason = ""; })}>Accept assignment</Button><Button variant="outline" disabled={!reason.trim()} onClick={() => mutate("University rejected; admin rerouting required", p => { p.assignment = "rejected"; p.status = "Needs rerouting"; p.reason = reason.trim(); })}>Reject</Button><Button variant="outline" disabled={!reason.trim()} onClick={() => mutate("University requested more information", p => { p.assignment = "info_requested"; p.reason = reason.trim(); })}>Request more info</Button></div></>}</>}
          {role === "industry_partner" && <><p className="text-sm">Offer prototype engineering, mentorship and testing support through {demoIndustry.name}.</p><Button data-testid="demo-interest" disabled={project.collaboration} onClick={() => mutate("Industry expressed interest and offered mentorship/support", p => { p.collaboration = true; })}>{project.collaboration ? "Collaboration active · Mentorship & prototyping" : "Express interest & offer support"}</Button></>}
          {role === "admin" && <><p className="text-sm">Assignment: {project.assignment} · {project.reason || "No outstanding assignment notes"}</p>{project.assignment === "rejected" && <Button onClick={() => mutate("Admin rerouted assignment to demo university", p => { p.assignment = "pending"; p.status = "Assigned"; })}>Reroute assignment</Button>}<p className="text-sm">Legal case: <strong>{project.legal.replaceAll("_", " ")}</strong></p><div className="flex flex-wrap gap-2"><Button disabled={project.proposal !== "submitted" || project.legal === "under_review" || project.legal === "approved"} onClick={() => mutate("Legal review started", p => { p.legal = "under_review"; })}>Review legal case</Button><Button disabled={project.legal !== "under_review"} onClick={() => mutate("Legal case approved", p => { p.legal = "approved"; })}>Approve</Button><Button variant="outline" disabled={project.legal !== "under_review"} onClick={() => mutate("Legal case rejected", p => { p.legal = "rejected"; })}>Reject case</Button><Button variant="outline" disabled={project.legal !== "under_review"} onClick={() => mutate("Legal revision requested", p => { p.legal = "needs_revision"; })}>Request revision</Button></div><p className="text-xs">Submit the university proposal before legal review. All funding shown is simulated.</p></>}
        </CardContent></Card>
        {(role === "university_admin" || role === "admin" || role === "industry_partner") && <Card><CardHeader><CardTitle className="flex items-center gap-2"><Users size={19} />Team, proposal & mentor history</CardTitle></CardHeader><CardContent className="space-y-4">
          <p className="text-sm">Students: {project.students.length}/6 · Mentors: {mentors.length}/2 · Proposal: {project.proposal}</p>
          {project.students.map(name => <p key={name} className="text-sm">{name} · Student · Computing · Year 3 · Active</p>)}
          {accepted && mentors.length === 0 && <Badge variant="outline">mentor_vacant · Replacement needed within 7 days (demo)</Badge>}
          {role === "university_admin" && <><div className="flex flex-wrap gap-2"><select className="rounded-md border bg-[hsl(var(--card))] p-2 text-sm" aria-label="Demo student" value={student} onChange={e => setStudent(e.target.value)}>{demoStudents.map(name => <option key={name}>{name}</option>)}</select><Button disabled={!accepted || project.students.length >= 6 || project.students.includes(student)} onClick={() => mutate(`Student joined: ${student}`, p => { p.students.push(student); })}>{project.students.length >= 6 ? "TEAM FULL" : "Add student"}</Button><Button disabled={!accepted || mentors.length >= 2} variant="outline" onClick={() => mutate("Faculty mentor assigned", p => { p.mentors.push({ name: `Demo Mentor ${p.mentors.length + 1}`, start: new Date().toISOString(), end: null, reason: "active" }); })}>Assign mentor</Button></div><Button data-testid="demo-proposal" disabled={!canDevelop || project.proposal === "submitted"} onClick={() => mutate("University proposal submitted", p => { p.proposal = "submitted"; p.status = "In progress"; })}>Submit proposal</Button><p className="text-xs">Accept the assignment and add a student and mentor before submitting a proposal.</p></>}
          <div className="space-y-2">{project.mentors.map((mentor, index) => <div key={index} className="rounded-lg border p-3 text-sm"><p>{mentor.name} · Faculty mentor · Water Resources</p><p>{new Date(mentor.start).toLocaleDateString()} → {mentor.end ? new Date(mentor.end).toLocaleDateString() : "Present"} · {mentor.reason}</p>{role === "university_admin" && !mentor.end && <Button variant="outline" size="sm" className="mt-2" onClick={() => mutate("Mentor resigned; history retained", p => { p.mentors[index].end = new Date().toISOString(); p.mentors[index].reason = "resigned"; })}>Resign mentor</Button>}</div>)}</div>
          <p className="text-sm">Industry support: {project.collaboration ? "Mentorship and prototyping active" : "Awaiting industry interest"}</p>
        </CardContent></Card>}
        <Card><CardHeader><CardTitle>Project milestones {role === "admin" ? "& demo disbursements" : ""}</CardTitle></CardHeader><CardContent className="space-y-3">{project.milestones.map((milestone, index) => <div key={milestone.name} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border p-3"><div><strong className="text-sm">{milestone.name}</strong><p className="text-xs">{milestone.completed ? "Completed" : "Pending"}{role === "admin" ? ` · ₹${milestone.amount.toLocaleString("en-IN")} · ${milestone.released ? "Demo release recorded" : "Unreleased"}` : ""}</p></div>{role === "university_admin" && <Button size="sm" disabled={project.proposal !== "submitted" || milestone.completed || (index > 0 && !project.milestones[index - 1].completed)} onClick={() => mutate(`${milestone.name} milestone completed`, p => { p.milestones[index].completed = true; if (p.milestones.every(m => m.completed)) p.status = "Completed"; })}>Complete milestone</Button>}{role === "admin" && <Button size="sm" disabled={project.legal !== "approved" || !milestone.completed || milestone.released} onClick={() => mutate(`${milestone.name} demo disbursement recorded`, p => { p.milestones[index].released = true; })}>Record demo disbursement</Button>}</div>)}{role === "admin" && <p className="text-xs">Legal approval and a completed milestone are required. No real money is transferred.</p>}</CardContent></Card>
        </div>
      </div>
      <Card><CardHeader><CardTitle>Demo activity timeline</CardTitle></CardHeader><CardContent>{workspace.history.length ? <ol className="space-y-3">{workspace.history.map(event => <li key={event.id} className="border-l-2 border-[hsl(var(--primary))] pl-3 text-sm"><p>{event.action}</p><p className="text-xs text-[hsl(var(--muted-foreground))]">{event.actor} · {new Date(event.at).toLocaleString()}</p></li>)}</ol> : <p className="text-sm text-[hsl(var(--muted-foreground))]">Demo actions will appear here as you work through the project.</p>}</CardContent></Card>
    </main>
  </div>;
}
